// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ColumnScanner is an autogenerated mock type for the ColumnScanner type
type ColumnScanner struct {
	mock.Mock
}

// Scan provides a mock function with given fields: src
func (_m *ColumnScanner) Scan(src interface{}) error {
	ret := _m.Called(src)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(src)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewColumnScanner creates a new instance of ColumnScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewColumnScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ColumnScanner {
	mock := &ColumnScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
