// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	gorp "github.com/go-gorp/gorp/v3"
	mock "github.com/stretchr/testify/mock"
	"reflect"
)

// Dialect is an autogenerated mock type for the Dialect type
type Dialect struct {
	mock.Mock
}

// AutoIncrBindValue provides a mock function with given fields:
func (_m *Dialect) AutoIncrBindValue() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoIncrBindValue")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AutoIncrInsertSuffix provides a mock function with given fields: col
func (_m *Dialect) AutoIncrInsertSuffix(col *gorp.ColumnMap) string {
	ret := _m.Called(col)

	if len(ret) == 0 {
		panic("no return value specified for AutoIncrInsertSuffix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*gorp.ColumnMap) string); ok {
		r0 = rf(col)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AutoIncrStr provides a mock function with given fields:
func (_m *Dialect) AutoIncrStr() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AutoIncrStr")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BindVar provides a mock function with given fields: i
func (_m *Dialect) BindVar(i int) string {
	ret := _m.Called(i)

	if len(ret) == 0 {
		panic("no return value specified for BindVar")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CreateIndexSuffix provides a mock function with given fields:
func (_m *Dialect) CreateIndexSuffix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateIndexSuffix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// CreateTableSuffix provides a mock function with given fields:
func (_m *Dialect) CreateTableSuffix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateTableSuffix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DropIndexSuffix provides a mock function with given fields:
func (_m *Dialect) DropIndexSuffix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DropIndexSuffix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IfSchemaNotExists provides a mock function with given fields: command, schema
func (_m *Dialect) IfSchemaNotExists(command string, schema string) string {
	ret := _m.Called(command, schema)

	if len(ret) == 0 {
		panic("no return value specified for IfSchemaNotExists")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(command, schema)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IfTableExists provides a mock function with given fields: command, schema, table
func (_m *Dialect) IfTableExists(command string, schema string, table string) string {
	ret := _m.Called(command, schema, table)

	if len(ret) == 0 {
		panic("no return value specified for IfTableExists")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(command, schema, table)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IfTableNotExists provides a mock function with given fields: command, schema, table
func (_m *Dialect) IfTableNotExists(command string, schema string, table string) string {
	ret := _m.Called(command, schema, table)

	if len(ret) == 0 {
		panic("no return value specified for IfTableNotExists")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(command, schema, table)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Placeholder provides a mock function with given fields: i
func (_m *Dialect) Placeholder(i int) string {
	ret := _m.Called(i)

	if len(ret) == 0 {
		panic("no return value specified for Placeholder")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QuerySuffix provides a mock function with given fields:
func (_m *Dialect) QuerySuffix() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for QuerySuffix")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QuoteField provides a mock function with given fields: field
func (_m *Dialect) QuoteField(field string) string {
	ret := _m.Called(field)

	if len(ret) == 0 {
		panic("no return value specified for QuoteField")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(field)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QuotedTableForQuery provides a mock function with given fields: schema, table
func (_m *Dialect) QuotedTableForQuery(schema string, table string) string {
	ret := _m.Called(schema, table)

	if len(ret) == 0 {
		panic("no return value specified for QuotedTableForQuery")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(schema, table)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SupportsCascade provides a mock function with given fields:
func (_m *Dialect) SupportsCascade() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsCascade")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SupportsLastInsertId provides a mock function with given fields:
func (_m *Dialect) SupportsLastInsertId() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsLastInsertId")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SupportsMultipleSchema provides a mock function with given fields:
func (_m *Dialect) SupportsMultipleSchema() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportsMultipleSchema")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ToSqlType provides a mock function with given fields: val, opts
func (_m *Dialect) ToSqlType(val *reflect.Type, opts gorp.ColumnOptions) string {
	ret := _m.Called(val, opts)

	if len(ret) == 0 {
		panic("no return value specified for ToSqlType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*reflect.Type, gorp.ColumnOptions) string); ok {
		r0 = rf(val, opts)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TruncateClause provides a mock function with given fields:
func (_m *Dialect) TruncateClause() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TruncateClause")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Dialect) Type() gorp.DialectType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 gorp.DialectType
	if rf, ok := ret.Get(0).(func() gorp.DialectType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(gorp.DialectType)
	}

	return r0
}

// NewDialect creates a new instance of Dialect. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialect(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dialect {
	mock := &Dialect{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
