// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DynamicTable is an autogenerated mock type for the DynamicTable type
type DynamicTable struct {
	mock.Mock
}

// SetTableName provides a mock function with given fields: _a0
func (_m *DynamicTable) SetTableName(_a0 string) {
	_m.Called(_a0)
}

// TableName provides a mock function with given fields:
func (_m *DynamicTable) TableName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewDynamicTable creates a new instance of DynamicTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamicTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamicTable {
	mock := &DynamicTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
