// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	context "context"

	gorp "github.com/go-gorp/gorp/v3"
	mock "github.com/stretchr/testify/mock"
)

// Hook is an autogenerated mock type for the Hook type
type Hook struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, executor
func (_m *Hook) Execute(ctx context.Context, executor gorp.SqlExecutor) error {
	ret := _m.Called(ctx, executor)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, gorp.SqlExecutor) error); ok {
		r0 = rf(ctx, executor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHook creates a new instance of Hook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hook {
	mock := &Hook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
