// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	gorp "github.com/go-gorp/gorp/v3"
	mock "github.com/stretchr/testify/mock"
)

// IntegerAutoIncrInserter is an autogenerated mock type for the IntegerAutoIncrInserter type
type IntegerAutoIncrInserter struct {
	mock.Mock
}

// InsertAutoIncr provides a mock function with given fields: exec, insertSql, params
func (_m *IntegerAutoIncrInserter) InsertAutoIncr(exec gorp.SqlExecutor, insertSql string, params ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, exec, insertSql)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InsertAutoIncr")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(gorp.SqlExecutor, string, ...interface{}) (int64, error)); ok {
		return rf(exec, insertSql, params...)
	}
	if rf, ok := ret.Get(0).(func(gorp.SqlExecutor, string, ...interface{}) int64); ok {
		r0 = rf(exec, insertSql, params...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(gorp.SqlExecutor, string, ...interface{}) error); ok {
		r1 = rf(exec, insertSql, params...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIntegerAutoIncrInserter creates a new instance of IntegerAutoIncrInserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIntegerAutoIncrInserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IntegerAutoIncrInserter {
	mock := &IntegerAutoIncrInserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
