// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	driver "database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// legacySqlTyper is an autogenerated mock type for the legacySqlTyper type
type legacySqlTyper struct {
	mock.Mock
}

// SqlType provides a mock function with given fields:
func (_m *legacySqlTyper) SqlType() driver.Valuer {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SqlType")
	}

	var r0 driver.Valuer
	if rf, ok := ret.Get(0).(func() driver.Valuer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Valuer)
		}
	}

	return r0
}

// newLegacySqlTyper creates a new instance of legacySqlTyper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newLegacySqlTyper(t interface {
	mock.TestingT
	Cleanup(func())
}) *legacySqlTyper {
	mock := &legacySqlTyper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
