// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// numberer is an autogenerated mock type for the numberer type
type numberer struct {
	mock.Mock
}

// ToInt64Slice provides a mock function with given fields:
func (_m *numberer) ToInt64Slice() []int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToInt64Slice")
	}

	var r0 []int64
	if rf, ok := ret.Get(0).(func() []int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	return r0
}

// newNumberer creates a new instance of numberer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newNumberer(t interface {
	mock.TestingT
	Cleanup(func())
}) *numberer {
	mock := &numberer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
