// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	driver "database/sql/driver"

	mock "github.com/stretchr/testify/mock"
)

// SqlTyper is an autogenerated mock type for the SqlTyper type
type SqlTyper struct {
	mock.Mock
}

// SqlType provides a mock function with given fields:
func (_m *SqlTyper) SqlType() driver.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SqlType")
	}

	var r0 driver.Value
	if rf, ok := ret.Get(0).(func() driver.Value); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(driver.Value)
		}
	}

	return r0
}

// NewSqlTyper creates a new instance of SqlTyper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSqlTyper(t interface {
	mock.TestingT
	Cleanup(func())
}) *SqlTyper {
	mock := &SqlTyper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
