// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// stringer is an autogenerated mock type for the stringer type
type stringer struct {
	mock.Mock
}

// ToStringSlice provides a mock function with given fields:
func (_m *stringer) ToStringSlice() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToStringSlice")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// newStringer creates a new instance of stringer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newStringer(t interface {
	mock.TestingT
	Cleanup(func())
}) *stringer {
	mock := &stringer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
