// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	gorp "github.com/go-gorp/gorp/v3"
	mock "github.com/stretchr/testify/mock"
)

// TargetedAutoIncrInserter is an autogenerated mock type for the TargetedAutoIncrInserter type
type TargetedAutoIncrInserter struct {
	mock.Mock
}

// InsertAutoIncrToTarget provides a mock function with given fields: exec, insertSql, target, params
func (_m *TargetedAutoIncrInserter) InsertAutoIncrToTarget(exec gorp.SqlExecutor, insertSql string, target interface{}, params ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, exec, insertSql, target)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for InsertAutoIncrToTarget")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(gorp.SqlExecutor, string, interface{}, ...interface{}) error); ok {
		r0 = rf(exec, insertSql, target, params...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTargetedAutoIncrInserter creates a new instance of TargetedAutoIncrInserter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTargetedAutoIncrInserter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TargetedAutoIncrInserter {
	mock := &TargetedAutoIncrInserter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
