// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	gorp "github.com/go-gorp/gorp/v3"
	mock "github.com/stretchr/testify/mock"
)

// TypeConverter is an autogenerated mock type for the TypeConverter type
type TypeConverter struct {
	mock.Mock
}

// FromDb provides a mock function with given fields: target
func (_m *TypeConverter) FromDb(target interface{}) (gorp.CustomScanner, bool) {
	ret := _m.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for FromDb")
	}

	var r0 gorp.CustomScanner
	var r1 bool
	if rf, ok := ret.Get(0).(func(interface{}) (gorp.CustomScanner, bool)); ok {
		return rf(target)
	}
	if rf, ok := ret.Get(0).(func(interface{}) gorp.CustomScanner); ok {
		r0 = rf(target)
	} else {
		r0 = ret.Get(0).(gorp.CustomScanner)
	}

	if rf, ok := ret.Get(1).(func(interface{}) bool); ok {
		r1 = rf(target)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// ToDb provides a mock function with given fields: val
func (_m *TypeConverter) ToDb(val interface{}) (interface{}, error) {
	ret := _m.Called(val)

	if len(ret) == 0 {
		panic("no return value specified for ToDb")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (interface{}, error)); ok {
		return rf(val)
	}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(val)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(val)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTypeConverter creates a new instance of TypeConverter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTypeConverter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TypeConverter {
	mock := &TypeConverter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
